version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_etl
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etl_db
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d  